[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coding-agent"
version = "0.1.0"
description = "An agent that can edit and perform QA on workflows"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.21.0",
    "claude-agent-sdk>=0.1.6",
    "llama-index-workflows>=2.9.1",
    "prompt-toolkit>=3.0.52",
    "rich>=14.1.0",
    "rich-gradient>=0.3.6",
    "vibe-llama-core>=0.2.0",
]

[tool.hatch.build.targets.wheel]
only-include = ["src/coding_agent"]

[tool.hatch.build.targets.wheel.force-include]
"../../AGENTS.modified.md" = "coding_agent/AGENTS.md"

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[project.scripts]
coder = "coding_agent.main:main"
